FROM debian:13
ARG DEBIAN_APT=http://debian.csail.mit.edu
ARG PVE_APT=https://us.mirrors.lierfang.com
ARG ARCH=




RUN rm /etc/apt/sources.list.d/*  \
&& echo "deb $DEBIAN_APT/debian trixie main contrib non-free non-free-firmware" >/etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  trixie-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  trixie-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian-security  trixie-security main contrib non-free non-free-firmware " >> /etc/apt/sources.list 


RUN apt update && apt install -y wget nano curl gnupg  ca-certificates apt-utils



RUN ARCH=$(dpkg --print-architecture) \
&& if [ "$ARCH" = "amd64" ]; then \
    echo "deb $PVE_APT/pxcloud/pxvirt trixie main" >> /etc/apt/sources.list;  \
    echo "deb $PVE_APT/pxcloud/devel trixie main" >> /etc/apt/sources.list; \
    curl -l -o /etc/apt/trusted.gpg.d/lierfang.gpg $PVE_APT/lierfang.gpg; \
else  \
    echo "deb [trusted=yes] $PVE_APT/pxcloud/pxvirt trixie main" >> /etc/apt/sources.list;  \
    echo "deb [trusted=yes] $PVE_APT/pxcloud/devel trixie main" >> /etc/apt/sources.list; \
    curl -l -o /etc/apt/trusted.gpg.d/lierfang.gpg $PVE_APT/pxcloud/lierfang.gpg; \
    curl -l -o /etc/apt/trusted.gpg.d/pveport.gpg $PVE_APT/pxcloud/pxvirt/pveport.gpg; \
fi

RUN apt update && apt -y install build-* devscripts cargo dh-cargo devscripts rsync debcargo pkg-config debhelper git bison dwarves flex meson equivs

RUN apt update  \
&& DEBIAN_FRONTEND=noninteractiv apt-get -y --no-install-recommends  install  proxmox-ve || echo ok 

RUN rm /var/lib/dpkg/info/pve-manager.postinst \
&& DEBIAN_FRONTEND=noninteractive dpkg --configure -a --force-confdef --force-confold


ADD ./start.sh /

CMD ["bash","/start.sh"]
