FROM debian:13
ARG DEBIAN_APT=http://deb.debian.org




RUN rm -f /etc/apt/sources.list.d/* \
&& echo "deb $DEBIAN_APT/debian trixie main contrib non-free non-free-firmware" >/etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  trixie-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  trixie-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb https://security.debian.org/debian-security  trixie-security main contrib non-free non-free-firmware " >> /etc/apt/sources.list


RUN apt update && apt install -y wget nano curl gnupg  ca-certificates apt-utils



RUN ARCH=$(dpkg --print-architecture) \
&& if [ "$ARCH" = "amd64" ]; then \
    echo "deb http://download.proxmox.com/debian/pve trixie pve-no-subscription" >> /etc/apt/sources.list;  \
    echo "deb http://download.proxmox.com/debian/devel trixie main" >> /etc/apt/sources.list; \
    wget -qO /etc/apt/trusted.gpg.d/proxmox-release-trixie.gpg \
        https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg; \
else  \
    echo "deb https://us.mirrors.lierfang.com/pxcloud/pxvirt trixie main" >> /etc/apt/sources.list;  \
    echo "deb https://us.mirrors.lierfang.com/pxcloud/devel trixie main" >> /etc/apt/sources.list; \
    curl -l -o /etc/apt/trusted.gpg.d/pveport.gpg \
        https://us.mirrors.lierfang.com/pxcloud/pxvirt/pveport.gpg; \
fi

RUN apt update && apt -y install build-* devscripts cargo dh-cargo devscripts rsync debcargo pkg-config debhelper git bison dwarves flex meson equivs liblocale-po-perl

RUN apt update  \
&& DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends  install  proxmox-ve || echo ok

RUN rm /var/lib/dpkg/info/pve-manager.postinst \
 && dpkg --force-confdef --force-confold --configure -a

RUN cargo install xtr

ENV PATH="/root/.cargo/bin:${PATH}"

ADD ./start.sh /

CMD ["bash","/start.sh"]
